[project]
name = "chicago-rstrips"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=3.1.0",
    "boto3>=1.40.47",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.5",
    "sodapy>=2.2.0",
    "dotenv",
]
